---
name: appdynamics_service_chat
pack: st2-chatops-aliases
description: Post to chat for Appdynamics events
enabled: true
trigger:
 type: st2.generic.notifytrigger
action:
 ref: chatops.post_message
 parameters:
   message: NAGIOS {{trigger.service}} ID:{{trigger.event_id}} STATE:{{trigger.state}}[{{ trigger.state_id }}]/{{trigger.state_type}}
     {{trigger.msg}}
   channel: 'hubot_testing'
