---
name: appdynamics_service_chat
pack: st2-chatops-aliases
description: Post to chat for Appdynamics events
enabled: true
trigger:
 type: st2-chatops-aliases.appdynamics_service_chat
action:
 ref: chatops.post_message
 parameters:
   message: Appdynamics {{trigger.msg}}
   channel: 'hubot_testing'
